apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: all-in-one-base
spec:
  params:
    - description: URL of the repository where Containerfile is stored
      name: GIT_REPOSITORY
      type: string
    - default: main
      description: URL of the repository where Containerfile is stored
      name: GIT_REPOSITORY_BRANCH
      type: string
    - default: ./Containerfile
      description: 'Containerfile path, relative'
      name: CONTAINERFILE_PATH
      type: string
    - default: .
      description: 'Podman Build Context'
      name: BUILD_CONTEXT
      type: string
    - description: 'Name of the image to create, i.e. quay.io/kubealex/image-mode-cicd'
      name: IMAGE_NAME
      type: string
    - description: 'Tags, separated by a space, to apply to the image'
      name: IMAGE_TAGS
      type: string
    - description: 'Name of the image to create, i.e. quay.io/kubealex/image-mode-cicd'
      name: FINAL_IMAGE_NAME
      type: string
    - description: 'Tags, separated by a space, to apply to the image'
      name: FINAL_IMAGE_TAGS
      type: string
    - default: 'false'
      description: TLS Verification
      name: TLS_VERIFY
      type: string
    - default: 'true'
      description: Generate QCOW2 Container image for OCPVirt ContainerDisk
      name: OCPVIRT_IMAGE_BUILD
      type: string
    - default: 'false'
      description: Store the intermediate image in the registry
      name: SKIP_INTERMEDIATE
      type: string
    - default: qcow2
      name: DESTINATION_IMAGE_FORMAT
      type: string
      description: 'Resulting image format - allowed: qcow2, anaconda-iso, vmdk, raw, ami, gcp'
    - default: |
        [[customizations.user]]
        name = "sysadmin"
        password = "redhat"
        groups = ["wheel"]
      description: config.toml content for customizations
      name: CONFIG_TOML_CONTENT
      type: string



  tasks:
    - name: git-clone
      description: Checks the Containerfile out from Git
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: $(params.TLS_VERIFY)
        - name: URL
          value: $(params.GIT_REPOSITORY)
        - name: REVISION
          value: $(params.GIT_REPOSITORY_BRANCH)
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: main-workspace
    - name: build-initial-image
      description: Builds the initial RHEL image from Containerfile.
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: IMAGE_TAGS
          value: $(params.IMAGE_TAGS)
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel9/podman:latest'
        - name: DOCKERFILE
          value: $(params.CONTAINERFILE_PATH)
        - name: CONTEXT
          value: $(params.BUILD_CONTEXT)
        - name: TLSVERIFY
          value: $(params.TLS_VERIFY)
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: $(params.SKIP_INTERMEDIATE)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: rhel-image-mode-build
      workspaces:
        - name: main-workspace
          workspace: main-workspace
        - name: cache-workspace
          workspace: cache-workspace
        - name: dockerconfig
          workspace: registry-creds
        - name: rhel-entitlement
          workspace: rhel-entitlements


    - name: bootc-image-builder
      description: Converts the initial image into a QCOW2 image file.
      params:
        - name: SOURCE_IMAGE
          value: $(params.IMAGE_NAME)
        - name: SOURCE_IMAGE_TAG
          value: $(params.IMAGE_TAGS)
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel9/bootc-image-builder:latest'
        - name: DEST_FORMAT
          value: $(params.DESTINATION_IMAGE_FORMAT)
        - name: CONFIG_TOML_CONTENT
          value: $(params.CONFIG_TOML_CONTENT)
        - name: TLS_VERIFY
          value: $(params.TLS_VERIFY)
      when:
        - input: "$(params.OCPVIRT_IMAGE_BUILD)"
          operator: in
          values: ["true"]
      runAfter:
        - build-initial-image
      taskRef:
        kind: Task
        name: bootc-image-builder
      workspaces:
        - name: main-workspace
          workspace: main-workspace
        - name: dockerconfig
          workspace: registry-creds

    - name: ocpvirt-containerfile-create
      description: Create a temporary Containerfile to generate the final image
      when:
        - input: "$(params.OCPVIRT_IMAGE_BUILD)"
          operator: in
          values: ["true"]
      runAfter:
        - bootc-image-builder
      taskRef:
        kind: Task
        name: ocpvirt-containerfile
      workspaces:
        - name: main-workspace
          workspace: main-workspace

    - name: ocpvirt-image-build
      description: Package the QCOW2 file into the final image and store it in the registry.
      when:
        - input: "$(params.OCPVIRT_IMAGE_BUILD)"
          operator: in
          values: ["true"]
      params:
        - name: IMAGE
          value: $(params.FINAL_IMAGE_NAME)
        - name: IMAGE_TAGS
          value: $(params.FINAL_IMAGE_TAGS)
        - name: TLSVERIFY
          value: $(params.TLS_VERIFY)
      runAfter:
        - ocpvirt-containerfile-create
      taskRef:
        kind: Task
        name: rhel-image-mode-build
      workspaces:
        - name: main-workspace
          workspace: main-workspace
        - name: dockerconfig
          workspace: registry-creds

  workspaces:
    - name: main-workspace
    - name: cache-workspace
    - name: registry-creds
    - name: rhel-entitlements
