FROM quay.io/fedora/fedora-bootc:42
#RUN dnf -y update && dnf -y install tmux mkpasswd
RUN dnf -y update
#RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && useradd -m -G wheel bootc-user -p $pass
#RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo
RUN dnf -y install qemu-guest-agent && \
    systemctl enable qemu-guest-agent
#RUN printf "Hi!  Welcome\nSystem: Fedora Bootc\nVersion: 45\n" > /etc/motd
