apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
  name: workshop-base-import-cron
  namespace: soe-run
spec:
  garbageCollect: Outdated
  importsToKeep: 2
  managedDataSource: workshop-base
  schedule: '*/2 * * * *'
  retentionPolicy: None
  template:
    metadata: {}
    spec:
      source:
        registry:
          url: docker://quay.io/dlederer/workshop-base-ocpv:latest
      storage:
        resources:
          requests:
            storage: 30Gi
