FROM quay.io/dlederer/workshop-base:latest


# Install only what is required and clean caches
RUN --mount=type=cache,target=/var/cache,sharing=locked \
    --mount=type=cache,target=/var/lib/dnf,sharing=locked \
    dnf remove --assumeyes chrony plymouth

# Ensure proper service states
RUN systemctl disable unwanted-service.service
